---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: 
  name: rhmap-snitch-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhmap-snitch
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: node
  spec:
    tags:
      - annotations:
          openshift.io/imported-from: 'node:8.1.2'
        from:
          kind: DockerImage
          name: 'node:8.1.2'
        generation: 2
        importPolicy: {}
        name: 8.1.2
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rhmap-snitch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhmap-snitch:latest
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/psturc/rhmap-snitch.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:8.1.2
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rhmap-snitch
  spec:
    replicas: 1
    selector:
      app: rhmap-snitch
      deploymentconfig: rhmap-snitch
    strategy:
      type: Rolling
    template:
      metadata:
        labels: 
          app: rhmap-snitch
          deploymentconfig: rhmap-snitch
      spec:
        containers:
        - env:
          - name: CONFIG_FILE
            value: "/var/log/node/config.json"
          image: rhmap-snitch
          imagePullPolicy: Always
          name: rhmap-snitch
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          volumeMounts:
          - mountPath: "/var/log/node"
            name: node-data-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: node-data-volume
          persistentVolumeClaim:
            claimName: nodestorage
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rhmap-snitch
        from:
          kind: ImageStreamTag
          name: rhmap-snitch:latest
      type: ImageChange

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: nodestorage
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: rhmap-snitch
    name: rhmap-snitch
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: rhmap-snitch
      deploymentconfig: rhmap-snitch

- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: rhmap-snitch
    name: rhmap-snitch
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: rhmap-snitch

